class zCMorphMesh {
 virtual void _GetClassDef();
 virtual void ~zCMorphMesh(uint);
 virtual void Render(zTRenderContext	&);
 virtual void IsBBox3DLocal();
 virtual void GetBBox3D();
 virtual void GetOBBox3D();
 virtual void GetVisualName();
 virtual void GetRenderSortKey();
 virtual void CanTraceRay();
 virtual void TraceRay(zVEC3 const &,zVEC3 const &,int,zTTraceRayReport &);
 virtual void GetFileExtension(int);
	virtual void GetAlphaTestingEnabled();
 virtual void SetAlphaTestingEnabled(int);
 virtual void LoadVisualVirtual(zSTRING const	&);
 virtual void StartAnimation(zSTRING	const &);
 virtual void StopAnimation(zSTRING const &);
 virtual void IsAnimationActive(zSTRING const &);
 virtual void GetAnyAnimation();
};
