class zCSkyControler_Outdoor {
 virtual void _GetClassDef();
 virtual void Archive(zCArchiver &);
 virtual void Unarchive(zCArchiver &);
 virtual void ~zCSkyControler_Outdoor(uint);
 virtual void SetTime(float);
 virtual void GetTime();
 virtual void ResetTime();
 virtual void SetFarZ(float);
 virtual void GetFarZ();
	virtual void SetFarZScalability(float);
 virtual void GetFarZScalability();
	virtual void SetBackgroundColor(zCOLOR);
 virtual void GetBackgroundColor();
 virtual void GetBackgroundColorDef();
 virtual void SetOverrideColor(zVEC3);
 virtual void SetOverrideColorFlag(int);
	virtual void GetCloudShadowScale();
 virtual void SetCloudShadowScale(float);
 virtual void UpdateWorldDependencies();
 virtual void GetDaylightColorFromIntensity(int);
 virtual void RenderSkyPre();
 virtual void RenderSkyPost(int);
 virtual void GetGlobalWindVec(zVEC3 &,zTAnimationMode);
 virtual void SetGlobalSkyScale(float);
 virtual void GetGlobalSkyScale();
 virtual void GetGlobalSkyScaleChanged();
 virtual void SetCameraLocationHint(zCSkyControler::zTCamLocationHint);
	virtual void SetWeatherType(zTWeather);
 virtual void GetRenderLightning();
};
