class zFILE {
	virtual ~zFILE();
	virtual void SetMode(long);
	virtual void GetMode();
	virtual void SetPath(zSTRING);
	virtual void SetDrive(zSTRING);
	virtual void SetDir(zSTRING);
	virtual void SetFile(zSTRING);
	virtual void SetFilename(zSTRING);
	virtual void SetExt(zSTRING);
	virtual void GetFileHandle();
	virtual void GetFullPath();
	virtual void GetPath();
	virtual void GetDirectoryPath();
	virtual void GetDrive();
	virtual void GetDir();
	virtual void GetFile();
	virtual void GetFilename();
	virtual void GetExt();
	virtual void SetCurrentDir();
	virtual void ChangeDir(bool);
	virtual void SearchFile(zSTRING const &,zSTRING const &,int);
	virtual void FindFirst(zSTRING const &);
	virtual void FindNext();
	virtual void DirCreate();
	virtual void DirRemove();
	virtual void DirExists();
	virtual void FileMove(zFILE *);
	virtual void FileMove(zSTRING,bool);
	virtual void FileCopy(zFILE *);
	virtual void FileCopy(zSTRING,bool);
	virtual void FileDelete();
	virtual void IsOpened();
	virtual void Create(zSTRING const &);
	virtual void Create();
	virtual void Open(zSTRING const &,bool);
	virtual void Open(bool);
	virtual void Exists(zSTRING const &);
	virtual void Exists();
	virtual void Close();
	virtual void Reset();
	virtual void Append();
	virtual void Size();
	virtual void Pos();
	virtual void Seek(long);
	virtual void Eof();
	virtual void GetStats(zFILE_STATS &);
	virtual void Write(void const *,long);
	virtual void Write(zSTRING const &);
	virtual void Write(char const *);
	virtual void Read(zSTRING &);
	virtual void Read(char *);
	virtual void Read(void *,long);
	virtual void ReadChar(char &);
	virtual void SeekText(zSTRING const &);
	virtual void ReadBlock(long,long);
	virtual void UpdateBlock(zSTRING const &,long,long);
	virtual void FlushBuffer();
	virtual void ReadCodeline(zSTRING &);
	virtual void ReadLines(zSTRING &,long);
	virtual void DirStepInto(zSTRING);
};
