class zCSoundSystem {
public:
	virtual ~zCSoundSystem();
	virtual void LoadSoundFX(zSTRING const &);
	virtual zCSoundFX* LoadSoundFXScript(zSTRING const &);
	virtual void GetSFXParser();
	virtual void GetPlayingTimeMSEC(zSTRING const &);
	virtual void SetSound3DDefaultRadius(float);
	virtual void GetSound3DDefaultRadius();
	virtual void SetMasterVolume(float);
	virtual void GetMasterVolume();
	virtual void PlaySound(zCSoundFX *,int,int,float,float) = 0;
	virtual void PlaySound(zCSoundFX *,int) = 0;
	virtual void PlaySound3D(zSTRING const &,zCVob *,int,zCSoundSystem::zTSound3DParams *) = 0;
	virtual void PlaySound3D(zCSoundFX *,zCVob *,int,zCSoundSystem::zTSound3DParams *) = 0;
	virtual void StopSound(int const &);
	virtual void StopAllSounds();
	virtual void GetSound3DProps(int const &,zCSoundSystem::zTSound3DParams &) = 0;
	virtual void UpdateSound3D(int const &,zCSoundSystem::zTSound3DParams *) = 0;
	virtual void GetSoundProps(int const &,int &,float &,float &);
	virtual void UpdateSoundProps(int const &,int,float,float);
	virtual void IsSoundActive(int const &);
	virtual void SetListener(zCVob *);
	virtual void SetGlobalReverbPreset(int,float);
	virtual void SetReverbEnabled(int);
	virtual void GetReverbEnabled();
	virtual void GetNumProvider();
	virtual void GetProviderName(int);
	virtual void SetProvider(int);
	virtual void SetSpeakerType(zCSoundSystem::zTSpeakerType);
	virtual void GetSpeakerType();
	virtual void SetGlobalOcclusion(float) = 0;
	virtual void GetCPULoad();
};
