class oCNpc_States {
	virtual void Archive(zCArchiver& arc);
	virtual void Unarchive(zCArchiver& arc);
	virtual void PackState(zCBuffer&);
	virtual void UnpackState(zCBuffer&);
	int     state_vtbl;
	zSTRING state_name;
	oCNpc*  state_npc;
	class TNpcAIState {
		TNpcAIState() = default;
		~TNpcAIState() = default;
		int      index = 0;
		int      loop  = 0;
		int      end   = 0;
		int      timeBehaviour = 0;
		zREAL    restTime = 0;
		int      phase = -1;
		zBOOL    valid = 0;
		zSTRING  name;
		zREAL    stateTime = 0;
		int      prgIndex = -1;
		zBOOL    isRtnState = 0;
	};
	TNpcAIState curState;
	TNpcAIState nextState;
	int             lastAIState;
	zBOOL           hasRoutine;
	zBOOL           rtnChanged;
	oCRtnEntry*     rtnBefore;
	oCRtnEntry*     rtnNow;
	zCRoute*        rtnRoute;
	zBOOL           rtnOverlay;
	int             rtnOverlayCount;
	int             walkmode_routine;
	zBOOL           weaponmode_routine;
	zBOOL           startNewRoutine;
	int             aiStateDriven;
	zVEC3           aiStatePosition;
	oCNpc*          parOther;
	oCNpc*          parVictim;
	oCItem*         parItem;
	int             rntChangeCount;
};

