struct zCSndFX_MSS : zCSoundFX {
	virtual ~zCSndFX_MSS();
	virtual void LoadResourceData();
	virtual void ReleaseResourceData();
	virtual void GetResSizeBytes();
	virtual void GetNumChannels();
	virtual void GetNumChannelFrames(int);
	virtual void GetChannelFrame(int,int);
	virtual void SetChannelFrame(int,int);
	virtual void GetPlayingTimeMSEC();
	virtual void GetPan();
	virtual void SetPan(float);
	virtual void GetVolume();
	virtual void SetVolume(float);
	virtual void GetFrequency();
	virtual void SetFrequency(int);
	virtual void SetLooping(int);
	virtual void IsLooping();
	virtual void SetIsFixed(int);
	virtual void GetIsFixed();
};
